// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYhkdGf65sq9I0RKFOefXBL1EOCys4IuY',
    appId: '1:827709933298:web:f4124352bbb607d383b26b',
    messagingSenderId: '827709933298',
    projectId: 'myfmapp-13672',
    authDomain: 'myfmapp-13672.firebaseapp.com',
    storageBucket: 'myfmapp-13672.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsV8jlV0PKqhK9B6LYtzN1j9FEhF9OCQs',
    appId: '1:827709933298:android:78741faf78fb5c0d83b26b',
    messagingSenderId: '827709933298',
    projectId: 'myfmapp-13672',
    storageBucket: 'myfmapp-13672.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF3dn1KPbhNCaP5t7bVbs8U4eQPEvLjdQ',
    appId: '1:827709933298:ios:da3237acec3673c183b26b',
    messagingSenderId: '827709933298',
    projectId: 'myfmapp-13672',
    storageBucket: 'myfmapp-13672.appspot.com',
    androidClientId: '827709933298-0m7p6t9h72m9mknaoq6lc7jln12d45cs.apps.googleusercontent.com',
    iosClientId: '827709933298-7fj26u6vi7odq6aoqnrq0ff7oauorqbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfm',
  );

}